# Generated by Django 4.0.1 on 2022-02-08 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mesage',
            new_name='message',
        ),
    ]
