# Generated by Django 4.0.1 on 2022-02-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_rename_mesage_post_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='topics',
            new_name='topic',
        ),
    ]
